### ISSUE TITLE
System modules

### ISSUE THREAD

**Issue by gobo7793** [gobo7793/Geckarbot#71]
**What's your feature request? Please describe the user story.**
As dev I want to
- use some core features of the but without caring for other plugins
- this includes most of the background features of the core plugins

**Describe the solution you'd like (acceptance criteria)**
- The bot should get some system modules which the plugins can interact with, unlike the bot utils which are only some utility functions
- Some plugins like the mod core plugin, which provides some of this core features, should be only the interaction layer with the user and provide the commands, not the background code

**Additional context or informations**
The current reactins bot utils module should also be a system module

**Comment by Fluggs** [comment]
I propose the following definitions:
* Plugins are modular files that provide commands for the user. They are completely optional from a technical standpoint.
* Core plugins are modular files that rely on specific global states in the bot itself or modify the behaviour of all other plugins. They don't have to be optional (I think).
* Utils are tools that don't require a global state management and can be used by plugins at will. Since plugins rely on them, they are not optional once implemented (and used).
* Subsystems (or whatever name we choose for this) are tools that require a global state management and can be used by plugins at will. They are not optional and their global state is handled by the bot itself.

**Comment by Fluggs** [comment]
Released in 1.5.0
